baseURL = "https://khursani.xyz/"
languageCode = "en-us"
title = "Sani's blog"
theme = "github-style"
googleAnalytics = "UA-123456-789"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Sani"
  description = "Full-stack developer"
  github = "khursani8"
  facebook = "khursani8"
  twitter = "khursani8"
  linkedin = "khursani8"
  instagram = "khursani8"
  tumblr = "khursani8"
  email = "khursani8@gmail.com"
  url = "https://khursani.xyz"
  keywords = "blog, google analytics"
  rss = true
  lastmod = true
  favicon = "/images/github.png"
  avatar = "/images/avatar.png"
  location = "Malaysia"
  userStatusEmoji = "ğŸ˜€"
  enableGitalk = true
    
  [params.gitalk]
    clientID = "80ebec365d98429560ea" # Your client ID
    clientSecret = "6e9f1163987ef63525f2b8c112849a65e6631543" # Your client secret
    repo = "blog" # æ‚¨çš„åšå®¢çš„githubåœ°å€Repository nameï¼Œä¾‹å¦‚ï¼šxxxx.github.io
    owner = "khursani8" # æ‚¨çš„GitHub ID
    admin = "khursani8" # æ‚¨çš„GitHub ID
    id = "location.pathname" # æ–‡ç« é¡µé¢çš„é“¾æ¥åœ°å€å°±æ˜¯ID
    labels = "gitalk" # Github issue labels. If you used to use Gitment, you can change it
    perPage = 15 # Pagination size, with maximum 100.
    pagerDirection = "last" # Comment sorting direction, available values are 'last' and 'first'.
    createIssueManually = true # è®¾ç½®ä¸ºtrueï¼Œå¦‚æœæ˜¯ç®¡ç†å‘˜ç™»å½•ï¼Œä¼šè‡ªåŠ¨åˆ›å»ºissueï¼Œå¦‚æœæ˜¯falseï¼Œéœ€è¦ç®¡ç†å‘˜æ‰‹åŠ¨æ·»åŠ ç¬¬ä¸€ä¸ªè¯„è®º(issue)
    distractionFreeMode = false # Enable hot key (cmd|ctrl + enter) submit comment.    
    proxy = "https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token" # å¯ä»¥è‡ªè¡Œæ·»åŠ åå‘ä»£ç†
  [[params.links]]
    title = "Link"
    href = "https://github.com/khursani8"
  [[params.links]]
    title = "Link2"
    href = "https://khursani.xyz"
    icon = "https://khursani.xyz/images/avatar.png"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
